### ISSUE TITLE
Increase font size for homepage welcome message

### ISSUE THREAD

**Issue by julia-smith** [INN/umbrella-ipbs#15]
`#front-page .left p {
    font-size: 1.5em;
}`

<img width="636" alt="screen shot 2017-08-09 at 9 34 33 am" src="https://user-images.githubusercontent.com/1643734/29127189-02ad1396-7ce6-11e7-873d-a8052af1b48a.png">

**Comment by benlk** [comment]
Resolved in 96a5649
