### ISSUE TITLE
Improve Member Station Map

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-ipbs#2]
1. Go to: http://ipbs.org
2. Look at the Member Stations map

RESULT: no color on map,  small font (even smaller for the animations with the station names), doesn’t look like it’s interactive

EXPECT 1: add color to map to encourage interaction
EXPECT 2: increase font size for key, map locations and station pop-outs
EXPECT 3: add roll-over state for locations or something else to make it obvious to click on them

(Above "EXPECTs" are suggestions. Overall, any suggestions are welcome to improve the UX of the map!)

**Comment by benlk** [comment]
Notes from the project intro meeting on 2017-07-14:

They're really excited about the interactive, like that it exists, like that it's interactive. So we need to keep at least a modicum of interactivity.

- [ ] increase colors
- [x] display dots for stations in unclicked state: this adds color
- [ ] add rollover states
- [x] speed up animations
- [x] increase font sizes
- [ ] mobile version?

**Comment by benlk** [comment]
As far as "increasing font sizes" goes - the text there is shapes, not text. I've replaced the city label text shapes with <text> elements and some CSS embiggening it, and this is what it looks like:

<img width="491" alt="screen shot 2017-07-28 at 5 44 41 pm" src="https://user-images.githubusercontent.com/1754187/28737450-9032e8fe-73bc-11e7-8d56-da79cf196fb9.png">

It's all one SVG. @julia67 is there a better way to do labels for this? Something that we can do in D3 or some other library that is easier to manipulate than manually editing nodes of an SVG? Or something that makes SVGs easier to edit? InkScape loses all of the class names when I edit this SVG, which kills the interactive.

Also, right now it's hard to add new items to the map, short of hauling out an SVG editor.

**Comment by julia-smith** [comment]
http://snapsvg.io/ is pretty good, and manual editing just in sublime might be the way to go if you need to add classes or data attributes or text blocks to the svg itself.

**Comment by benlk** [comment]
- [x] increase top and bottom spacing on this svg to prevent these from conflicting

![image](https://user-images.githubusercontent.com/1754187/28891043-262c4598-7797-11e7-9b84-77a6985442e9.png)

**Comment by benlk** [comment]
From Slack:

> ... why is that map even in an iframe? 😦 
> :thinking: 
> ✈️ 

@kaylima Can you ask them if it is important that this graphic remain as an embedded iframe? This would work a lot better with the SVG directly within the page.

**Comment by kaylima** [comment]
> @kaylima Can you ask them if it is important that this graphic remain as an embedded iframe? This would work a lot better with the SVG directly within the page.

"Change as you see fit."

**Comment by benlk** [comment]
Post-#12 homepage is now deployed to staging, with the SVG directly on the homepage. Top and bottom spacing has been increased, and the last of the path-based labels are now converted to text labels that are styled through CSS.

<img width="549" alt="screen shot 2017-08-08 at 10 16 38 pm" src="https://user-images.githubusercontent.com/1754187/29102466-4c0e21e2-7c87-11e7-8326-9d47f546a9f3.png">
<img width="554" alt="screen shot 2017-08-08 at 10 16 45 pm" src="https://user-images.githubusercontent.com/1754187/29102465-4c0d91a0-7c87-11e7-8e8d-14b297b84da5.png">

**Comment by benlk** [comment]
From feedback last week:

> "I cannot read the map. It is very small."

- [ ] ~~test on low-dpi screen~~ (https://www.html5rocks.com/en/tutorials/developertools/mobile/)
- [ ] ~~resize text to be bigger~~

**Comment by benlk** [comment]
Above bits do not need to be done; it seems to be fine on lower-DPI screens, and when that user ^ switched from an antique browser to Edge, they had no problems.

Here's the smallest that map will appear, on a 17" 1440x900 screen, effectively 99.89 PPI:

<img width="448" alt="screen shot 2017-08-14 at 12 30 09 pm" src="https://user-images.githubusercontent.com/1754187/29281288-69bb95c6-80ec-11e7-8a85-4b9fdee8193a.png">

It seems okay to us.
