### ISSUE TITLE
Homepage map: collapse per-transmitter dots to single dot per general area

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-ipbs#20]
The current map has different dots on the map for each transmitter:

<img width="428" alt="screen shot 2018-05-17 at 1 03 59 pm" src="https://user-images.githubusercontent.com/1754187/40192590-d341d590-59d2-11e8-9ff4-ec99190ac278.png">

IPBS would like to replace the per-transmitter dot with larger per-area dots. This will require editing the SVG.

### Questions that will need to be addressed:

- [ ] How should the transmitters that don't match obvious geographic clusters be handled? There's one north of Fort Wayne and east of Elkhart, and one NNW of Muncie and SW of Fort Wayne.

**Comment by tylermachado** [comment]
The version of the SVG I downloaded already hides the individual transmitter dots until the central gray ones are clicked. I am increasing the radius of those central gray ones.
