### ISSUE TITLE
Add more station logos to homepage slider area

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-ipbs#22]
- [x] add the new logos that IPBS conveyed in a request to @kaylima 
- [x] provide docs for adding new logos if those docs do not exist

It looks like these are handled by a custom post type: https://github.com/INN/umbrella-ipbs/blob/master/wp-content/themes/ipbs/front-page.php#L38-L61

**Comment by benlk** [comment]
This requires no coding.

The steps to upload a new station logo are as follows:

1. Log in to http://ipbs.org/wp-admin/
2. Go to http://ipbs.org/wp-admin/edit.php?post_type=station and click the "Add New" button
3. Create the new station
    1. Give the station a title.
    2. Enter the station's website URL in the "Station Details" box
    3. Check the box for the appropriate city for the station
    4. Check the box for the appropriate station type: TV and/or Radio
    5. In the "Featured Image" box, upload an image containing the station's logo.
    6. Click the "Publish" button
4. Visit http://ipbs.org/ to verify that the new logo has been added.

**Comment by kaylima** [comment]
![wfiulogo-01](https://user-images.githubusercontent.com/15877728/41176054-5f2f2b5c-6b1c-11e8-9ccc-03b615f06171.png)
![wvub logo](https://user-images.githubusercontent.com/15877728/41176058-6345e7e4-6b1c-11e8-928b-064a6930eb5f.jpg)
![wvut logo](https://user-images.githubusercontent.com/15877728/41176059-635c2a90-6b1c-11e8-8558-cb7f7568ceb1.jpg)

Logos to upload ^

**Comment by benlk** [comment]
I see these on http://ipbs.org/ now.
