### ISSUE TITLE
logos aren't showing as expected in carousel

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-ipbs#28]
1. Go to: http://ipbs.org/ and look at logos

RESULT: the following logos should be next to each other, and they aren't:
- WFYI-TV & WFYI-FM - Indianapolis
- WIPB-TV & WBST-FM

They're grouped together by publishing date but aren't appearing in that order.

EXPECT: fix so that they're placed next to each other

**Comment by tylermachado** [comment]
Looks like this is where the slider is assembled and ordered. Apparently by "random", which is not what testing seemed to suggest. Investigation ongoing. https://github.com/INN/umbrella-ipbs/blob/d8295bc848b0b65c7d296acc4837baca1b9badec/wp-content/themes/ipbs/front-page.php#L48
