### ISSUE TITLE
Public Page for Content Sharing

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-ipbs#3]
1. Go to: http://ipbs.org
RESULT: no page for public content sharing
EXPECT: create a page that will have:
1. Page title and intro copy
2. Multiple titles/headlines and descriptions/excerpts of stories brought in by RSS
3. Headline/excerpt will link out to member station sites

From client:
“Create a public facing page which briefly describes station produced content in headline fashion. The page could be topical in nature and updated every 30 days. The page could reside at IPBS.org (or a station’s website.) When a topical program headline description is selected, a link takes the visitor to the station’s web archive for further detail and video.”

**Comment by benlk** [comment]
This can be done with Link Roundups, and literally be a Link Roundups archive.

Do we want to take that route, or do something different?

**Comment by julia-smith** [comment]
A Links Roundups archive sounds great to me.

**Comment by benlk** [comment]
This needs some compatibility partials, I think. The saved links aren't displaying as links. http://ipbs.staging.wpengine.com/?post_type=rounduplink

**Comment by benlk** [comment]
Compatibility template created; now deployed.

**Comment by benlk** [comment]
Docs for the Link Roundups plugin's Saved Links feature, which powers this, are here: https://github.com/INN/link-roundups/blob/master/docs/saved-links.md
