### ISSUE TITLE
Homepage template setup

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#40]

**Comment by joshdarby** [comment]
@MirandaEcho Does this one and #41 need estimates also?

**Comment by joshdarby** [comment]
@MirandaEcho Where would I find the design for this one?

**Comment by joshdarby** [comment]
Homepage design: https://drive.google.com/file/d/1nWX3FdStYYRg9-qZaAtMBMD74b_m6xCE/view
