### ISSUE TITLE
Site Navigation & Header

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#43]
logo as header (left aligned)
two menu sections
styling

<img width="1236" alt="Screen Shot 2020-01-15 at 6 44 18 PM" src="https://user-images.githubusercontent.com/48263361/72483573-16dfb280-37c7-11ea-908b-c7ea16cc0f7e.png">

Logo: https://drive.google.com/open?id=1TDJdcvmyGbhBGKUs3qclYdn6ehhQip08

**Comment by joshdarby** [comment]
I don't think this one will take too long, but I'm hesitant to say 2 hours, so I'll go with 4 since we'll need to account for the mobile version as well.

**Comment by MirandaEcho** [comment]
@joshdarby - is this still blocked? is there additional info on the designs that we need to continue?

**Comment by MirandaEcho** [comment]
Update from Client feedback:
"The logo needs to be a little larger.  It looks out of proportion relative to the image and content beneath.  The space between the logo and the navigation bar is too big.  The space between the logo and above the image is too small.  Go too IndianapolisSymphony.org for a reference. "

Also just a note that "Internal Directory" should just be "Directory" and "Underwriting" to "Underwriting and Sponsorship"

**Comment by joshdarby** [comment]
@MirandaEcho I set this one (and the footer/pre-footer) as blocked since I knew I would need to come back to it once we had finalized fonts and colors.
