### ISSUE TITLE
Mobile navigation

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#44]
https://drive.google.com/open?id=1Z_IOB71UNYRNSvudrvFiwSZh3yvSR0Sk

**Comment by joshdarby** [comment]
@MirandaEcho Where can I find the design for this?

**Comment by MirandaEcho** [comment]
@joshdarby - link updated

**Comment by joshdarby** [comment]
I'm going to go with what I said for #43 and say that I think this will take over 2 hours but under/around 4.

**Comment by benlk** [comment]
This looks like everything on the right-hand side of the menu in #43 collapses into a single "Menu" button, below a certain viewport size.

Is either the mobile or desktop nav supposed to be sticky? Or do they remain at the top of the site?

**Comment by MirandaEcho** [comment]
@kaylima Thoughts on stickiness? I'm leaning sticky on mobile if possible, non-sticky on desktop.

**Comment by kaylima** [comment]
@MirandaEcho  agreed for non-sticky on desktop, and for mobile, let's do what's easiest based on existing Largo functionality
