### ISSUE TITLE
Prefooter (sponsors section)

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#45]
<img width="817" alt="Screen Shot 2020-01-15 at 6 48 36 PM" src="https://user-images.githubusercontent.com/48263361/72483727-ad13d880-37c7-11ea-955e-ac9fca617ead.png">

- [ ] Needs to hide if empty
- [x] We might want to use a plugin for the logo slider - lets discuss

**Comment by joshdarby** [comment]
Assuming we can just reuse the same [logo slider plugin](https://wordpress.org/plugins/tc-logo-slider/) that we did for Workday, this should be around 2 hours.
