### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#46]
<img width="1271" alt="Screen Shot 2020-01-15 at 6 49 59 PM" src="https://user-images.githubusercontent.com/48263361/72483796-d7659600-37c7-11ea-838d-42b190c11b01.png">

**Comment by joshdarby** [comment]
This should also be around 2 hours.

**Comment by benlk** [comment]
This looks like largo's narrow-wide-narrow three-column option, with rules for the nav menu widget in the middle to make sure it wraps into columns like that. The "Our Stations" item would be a nav menu widget, with the stations contained as custom menu items linking to their websites (or some other link)
