### ISSUE TITLE
Improve spacing

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-ipbs#5]
1. Go to http://ipbs.org/?page_id=52

RESULT: <"p"> spacing is way to large
EXPECT: update <"p"> style

**Comment by benlk** [comment]
Created a page for testing this: http://ipbs.staging.wpengine.com/?page_id=346

And a post: http://ipbs.staging.wpengine.com/?p=347

We're gonna want to address p, ol li, ul li, and h2 styles.

**Comment by benlk** [comment]
First pass completed on styles; @julia67 take a look if you want to. 

Basically:
- paragraph-paragraph space is 1em; line height is 1.2
- no space between li other than line height
- add styles for h4 and blockquote
