### ISSUE TITLE
Homepage: Top section

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#55]
<img width="855" alt="Screen Shot 2020-01-23 at 6 08 50 PM" src="https://user-images.githubusercontent.com/48263361/73034737-69465200-3e0b-11ea-85db-f4497b6319cf.png">

- Header image will be set separately, not based on a featured article. Use the one from the design or the one from their current site for now, a final one is forthcoming.
- Text should be a text field that can be entered, rather than automatically pulling from an internal page
- Option for "more" link should exist under the text section as well
- Quick links will be links to internal pages

**Comment by benlk** [comment]
2h on the styles and any necessary markup tweaks; the markup was started in https://github.com/INN/umbrella-ipbs/pull/51

**Comment by benlk** [comment]
- What content does the client want to feature in this area? That affects whether we'll make this a post or page or other configuration like having a widget area for `.inner`.
- Waiting on their photoshoot for that image, which will probably be the same for an entire year.

But:
- We know this will not be auto-populated
- If it's a text widget, they can make it link wherever

So:
- let's go ahead and make this into a widget area.

**Comment by benlk** [comment]
@MirandaEcho do we have that image somewhere, or should we use a placeholder until they provide us with the results of the photoshoot?

**Comment by benlk** [comment]
Nevermind, I was able to grab the following from inspecting Adobe XD:

    component.png PNG 1050x700 1050x700+0+0 8-bit sRGB 705622B 0.000u 0:00.009

**Comment by benlk** [comment]
With #80 and #81 merged, the template work and styling is ready for QA.
