### ISSUE TITLE
Homepage: Our Impact Section

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#56]
<img width="855" alt="Screen Shot 2020-01-23 at 6 12 09 PM" src="https://user-images.githubusercontent.com/48263361/73034872-dfe34f80-3e0b-11ea-89c2-83934d232f05.png">

- These should be text and image widgets with the ability to link to an internal page.

**Comment by benlk** [comment]
Are these not a category of posts?

This is the nested-image-widget problem again.

If they're a category of posts, then this is a Largo Recent Posts widget with some custom styles. Nothing else on the homepage would be a Largo Recent Posts widget, except maybe the Features  section in #59, and the difference between these two Largo Recent Posts widgets would be the widget background chosen: default for this design's black text and light blue background, or "reverse" for white text and blue background of the Features heading. Styling: **2h**, once we get that swooshy background image.

If this is three side-by-side images with their captions and links, then we're getting into "custom code in an HTML widget" territory unless we're willing to write a custom three-image widget. (Did we do that for SFPP or someone else recently?)

**Comment by joshdarby** [comment]
> Did we do that for SFPP or someone else recently?

Kind of. We created a "promo box" widget for SFPP which includes the ability to upload an image.

https://github.com/INN/umbrella-sfpublicpress/pull/49

**Comment by MirandaEcho** [comment]
Edit: Three static images and text works for this, without links.

**Comment by benlk** [comment]
Investigate the Gallery widget.
