### ISSUE TITLE
Member Stations: Station list

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#58]
<img width="865" alt="Screen Shot 2020-01-23 at 6 13 41 PM" src="https://user-images.githubusercontent.com/48263361/73034940-17ea9280-3e0c-11ea-82d3-8cfe0c03d7f5.png">

**Comment by benlk** [comment]
Member stations are stored as a custom post type.

Is this displaying _all_ member stations or just a select few? In any particular order?

**Comment by benlk** [comment]
- all stations
- no controls

So then it's a widget, looping through the custom post type: 4h, for widget and styling and overhead.
