### ISSUE TITLE
Update permalink structure

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-ipbs#6]
1. Go to: http://ipbs.org/wp-admin/options-permalink.php

RESULT: set to "plain"
EXPECT: should be updated to post name for SEO, existing content needs to be updated, and redirects need to be created for existing content

**Comment by benlk** [comment]
Do they just want post name, or do they also want dates? https://codex.wordpress.org/Using_Permalinks#Choosing_your_permalink_structure

**Comment by kaylima** [comment]
Please set to "Day and name". Thanks!

**Comment by benlk** [comment]
Year-month-day or just year-month?

**Comment by benlk** [comment]
This is configured on staging: 

- http://ipbs.staging.wpengine.com/rounduplink/
- http://ipbs.staging.wpengine.com/2016/06/23/better-together-restoring-the-american-community/
