### ISSUE TITLE
Interior Page: Block styling for sidebar blocks

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#61]
https://drive.google.com/open?id=1olwa0muvPm3SVeEGSI33BaL9awTO3RYM

NOTE: There should also be a version for each color like this:
![Screen Shot 2020-01-23 at 6 26 43 PM](https://user-images.githubusercontent.com/48263361/73035503-ec68a780-3e0d-11ea-84e1-96ff3da64a09.png)

**Comment by benlk** [comment]
So we have:

- default, uncolored group block
- 4 solid-background colors from the color picker
- 4 border-top colors from the same color picker

Color picker will be established in #62, but if we want the bordered alternative model, we'll want to add a variation selector that changes the style from background to border, and appropriate styles within the editor and on the frontend.

- variation selector: 2h
- styles: 4-6h (being pessimistic about Editor styles)
