### ISSUE TITLE
Button Styles

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#63]
<img width="396" alt="Screen Shot 2020-01-23 at 6 28 15 PM" src="https://user-images.githubusercontent.com/48263361/73035556-1fab3680-3e0e-11ea-81ec-3a8ff8dfdde7.png">

**Comment by benlk** [comment]
- Button mixin, applied to:
    - .btn and .btn-primary classes
    - Button block, in a way that doesn't override the colors set by the color picker in the Button block (we did this recently)

2h?
