### ISSUE TITLE
Job board

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-ipbs#75]
Landing page that displays the job board postings with these styles:

![jobs-board-2 (1)](https://user-images.githubusercontent.com/48263361/73406996-7eb0f580-42bd-11ea-8b33-b9b97ecc64b5.png)

**Comment by benlk** [comment]
Were we having the job board powered by a dedicated job-board plugin?

**Comment by MirandaEcho** [comment]
Currently they're custom post types, correct? Pros and cons of keeping that approach vs a plugin instead?

**Comment by benlk** [comment]
If we set Dashboard > CPT UI > Edit Post Types > Jobs > Settings > Has Archive to True, then https://ipbs.test/?post_type=job looks like this:

![Screen Shot 2020-01-29 at 19 13 19](https://user-images.githubusercontent.com/1754187/73408885-95f6df80-42cb-11ea-8108-06b6aaac23c3.png)

If IPBS likes their current system for posting jobs, then alll we'll need to do is create a custom template for that archive, and custom post templates. Which we'd do anyways if we were switching to a different jobs plugin.

**Comment by MirandaEcho** [comment]
@benlk  and @joshdarby I need an estimate for this please. Thanks!

**Comment by benlk** [comment]
I'd estimate 6h total, between the post template, the archive template, and any weirdness that may come from CPT UI or ACF.

**Comment by joshdarby** [comment]
I think 6 hours is fair if we're just adding basic styles to the CPT jobs post template. If we do anything beyond basic styling for it I'd think 8 would be a better guesstimate, just in case.

**Comment by joshdarby** [comment]
@MirandaEcho What's our plan for design for the job post template?
